# Generated by Django 5.1.4 on 2025-01-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('preparation_time', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
