# Generated by Django 5.1.4 on 2025-01-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('reservation_status', models.CharField(choices=[('Available', 'Trống'), ('Occupied', 'Đang sử dụng'), ('Reserved', 'Đã đặt trước')], default='Available', max_length=20)),
            ],
            options={
                'db_table': 'tables',
            },
        ),
    ]
